config/routes.rb
Cingo::Application.routes.draw do

  resources :websites

  root :to => "home#index"

  devise_for :users,:controllers  => {
             :registrations => 'users/registrations',
             :sessions =>'users/sessions',
             :passwords => "users/passwords"
           }

  match 'auto_fill' => 'websites#auto_fill', :as => :auto_fill
  match 'get_info' => 'websites#get_info', :as => :get_info

  match 'setup' => 'websites#setup', :as => :setup

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  CERT_DIR = "/home/deploy/cingo/newCA/"

  # Setup accessible (or protected) attributes for your model
  attr_accessible :cert_name,:export,:cert,:country_code,:email, :password, :password_confirmation, :remember_me,:first_name, :last_name,:phone_number
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :phone_number, :presence => true 
  validates :country_code, :presence => true

  before_save :set_phone_number
  has_many :websites, :dependent => :destroy
  # attr_accessible :title, :body
  #before_destroy :remove_files

  after_create :send_cert

  def set_phone_number
    if self.phone_number.present?
      self.phone_number = self.phone_number.gsub("-","").gsub("(","").gsub(")","").gsub(" ","")
    end
    self.export = self.password if !self.export.present? && self.new_record?
  end

  def send_cert
    create_p12
    Notice.welcome(self.id).deliver
  end

  def phone
    "#{self.country_code}-#{self.phone_number}"
  end

  def name
    "#{first_name} #{last_name}"
  end

  def create_p12
    subj = "/C=US/ST=Texas/L=Austin/O=Cingo/OU=Cingo/CN=#{self.name} (#{self.email})/emailAddress=#{self.email}"
    self.cert_name = "#{self.first_name.downcase}_#{self.last_name.downcase}"
    self.save
    dir_name  = "#{CERT_DIR}#{self.id}"
    Dir.mkdir(dir_name) unless File.directory?(dir_name)
    create_cert(subj)
    sign_cert
    generate_p12
    export_cert_to_db
    #system("openssl pkcs12 -export -in #{CERT_DIR}server_cert.pem -inkey #{CERT_DIR}new_server_key.pem -out #{CERT_DIR}#{self.id}/#{self.cert_name}.p12 -passout pass:#{self.export}")        
  end

  def create_cert(subj)
    system("openssl req -new -sha1 -newkey rsa:1024 -nodes -keyout #{CERT_DIR}#{self.id}/#{self.cert_name}.key -out #{CERT_DIR}#{self.id}/#{self.cert_name}.csr -subj '#{subj}'")
  end

  def sign_cert
    system("openssl ca -batch -config /usr/lib/ssl/openssl.cnf -policy policy_anything -extensions ssl_client -out #{CERT_DIR}#{self.id}/#{self.cert_name}.crt -infiles #{CERT_DIR}#{self.id}/#{self.cert_name}.csr")
  end

  def generate_p12
    system("openssl pkcs12 -export -clcerts -in #{CERT_DIR}#{self.id}/#{self.cert_name}.crt -certfile #{CERT_DIR}demoCA/cacert.pem -inkey #{CERT_DIR}#{self.id}/#{self.cert_name}.key -out #{CERT_DIR}#{self.id}/#{self.cert_name}.p12 -name '#{self.name}' -passout pass:#{self.export} ")
  end

  def export_cert_to_db
    f=File.read("#{CERT_DIR}#{self.id}/#{self.cert_name}.crt")
    self.cert = f.split("BEGIN CERTIFICATE")[1].split("END CERTIFICATE")[0].gsub("-","").gsub("\n","")
    self.save
  end
end

app/models/website.rb
class Website < ActiveRecord::Base
  attr_accessible :url, :user_name,:password,:salt
  belongs_to :user

  validates :url, :presence => true
  #validates :url, url: true
  validates_format_of :url ,with: /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix

  validates :user_name, :presence => true
  validates :password, :presence => true

  before_validation :check_url
  before_save :encrypt_password

  def check_url
  	if self.url.include? "http"
  	else
  		self.url = "http://#{url}"
  	end
  end

  def encrypt_password
    self.salt = Devise.friendly_token.to_s+Devise.friendly_token.to_s if !self.salt.present?
    a=ActiveSupport::MessageEncryptor.new(self.salt)
    self.password = a.encrypt_and_sign(self.password) 
  end

  def decrypt
    a=ActiveSupport::MessageEncryptor.new(self.salt)
    a.decrypt_and_verify(self.password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :layout_by_resource

  def layout_by_resource
    if params[:controller] == "home"
      "application"
    else
      "layout_header"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	Rails.logger.info request.inspect
  	Rails.logger.info request.env["X-SSL-Client-S-DN"] if request.env["X-SSL-Client-S-DN"].present?
  	redirect_to websites_path if current_user
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	def create
		params[:user][:phone_number] = params[:phone_number]
		params[:user][:country_code] = params[:country_code]
		
		super	
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

	before_filter :authenticate_user!, except: [:auto_fill]

  def index
  end

  def setup    
  end

  def auto_fill
    Rails.logger.info request.inspect
    pcert = request.env["HTTP_X_SSL_CLIENT_S_DN"]
    if pcert.present?
      @cert = true
      Rails.logger.info request.inspect
      pcert = pcert.gsub("-----BEGIN CERTIFICATE-----","").gsub("-----END CERTIFICATE-----","").gsub("\n","").gsub("\t","")
      Rails.logger.info pcert
      @user = User.where(email: params[:e], cert: pcert).last      
      if @user.present?
        urls = @user.websites.collect(&:url)
        extract_url = extract_domain(params[:url])
        #[params[:url].split("/")[2].split(".")[0],params[:url].split("/")[2].split(".")[1]]
        @website = @user.websites.find_all{|website| website.url.include? extract_url}.last       
      end
    else
      @cert = nil
    end
  	respond_to do |format|
  		format.js {}
  	end
  end


  def extract_domain(url)
    require 'uri'
    domain = URI.parse(url).host.split('.')

    raise Exception.new("Invalid host") if domain.length < 2

    if (domain[-1].length == 2) and (domain[-2].length == 3 || domain[-2].length == 2)
      return domain[-3..-1].join('.')
    else
      return domain[-2..-1].join('.')
    end
  end

  def get_info
  	
  	respond_to do |format|
  		format.js {}
  	end
  end

  def new
  	@website = current_user.websites.new
  end

  def create
  	@website = current_user.websites.new(params[:website])
  	if @website.save
  		flash[:notice] = "Website added successfully"
      redirect_to setup_path
  	else
  		render "new"
  	end
  end

  def edit
  	@website = current_user.websites.find(params[:id])
  end

  def update
  	@website = current_user.websites.find(params[:id])
  	if @website.update_attributes(params[:website])
      flash[:notice] = "Website updated successfully"
  		redirect_to setup_path
  	else
  		render "edit"
  	end
  end

  def destroy
  	@website = current_user.websites.find(params[:id])
  	@website.destroy
    flash[:notice] = "Website removed successfully"
  	redirect_to setup_path	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def get_link
		secret_key = current_user.email
		key = current_user.email.split("@").first
		encrypted = "#{Encryptor.encrypt(secret_key,key: key)}--#{key}".html_safe
			# var ;
		"javascript:(function(){
				var h,l,s;
				var e='#{secret_key}';
				var _CINGO={
					url:'https://ec2-54-85-41-230.compute-1.amazonaws.com/auto_fill.js',
					l:encodeURIComponent(location.href),
					s:document.createElement('script'),
					h:document.getElementsByTagName('head')[0]
				};
				var s= _CINGO.s;
				s.src=_CINGO.url+'?url='+_CINGO.l+'&e='+e;
				document.getElementsByTagName('head')[0].appendChild(s);					
				})()"

	end

	def extract_domain(url)
    require 'uri'
    domain = URI.parse(url).host.split('.')
    raise Exception.new("Invalid host") if domain.length < 2
    URI.parse(url).host
  end

  def active_menu(controller,action)
  	return "active" if params[:controller] == controller && params[:action] == action
  	""
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/home/index.html.erb
<style>
#feature_slider1{
margin-top: 32px;
background-image: url("assets/background.jpg");
background-size: auto;
padding-top: 51px;
padding-bottom: 51px;
background-repeat: no-repeat no-repeat;
padding-bottom: 400px;
background-position: 55% 70px;
}
#feature_slider1 .container .title {
color: #000;
line-height: 1.2;
text-transform: uppercase;
text-shadow: 0 0 1px #fff,0px 1px 2px rgba(0,0,0,0.5);
margin-top: 18%;
font-size: 50px;
}
</style>

<section id="feature_slider1" class="lol">
  <div class="container">
  	<div class="title big">
			<div style="text-align: left;">
				<span style="font-size: 80%;">Stop trying to </span>
			</div>
			<div style="text-align: left;">
				<span style="font-size: 80%;">remember passwords</span>
			</div>			
		</div>
  </div>
</section>
<div id="how_it_works" style="min-height:40px;">
  &nbsp;
</div>
<div id="showcase">
  <div class="container">
    <div class="section_header">
      <h1 style ="text-align:center">HOW IT WORKS</h1>
    </div>            
    <div class="row feature_wrapper">
      <!-- Features Row -->
      <div class="features_op1_row">
        <!-- Feature -->
        <div class="col-sm-3 feature first">
          <div class="img_box">            
              <%= image_tag "Icon1.png"%>                       
          </div>
          <div class="text">
            <p>
                Sign up and receive free Digital Id
            </p>
          </div>
        </div>
        <!-- Feature -->
        <div class="col-sm-3 feature">
          <div class="img_box">
            
              <%= image_tag "Icon2.png"%>
              
          </div>
          <div class="text">
            <p>
                Add or import your favorite websites
            </p>
          </div>
        </div>
        <!-- Feature -->
        <div class="col-sm-3 feature last">
          <div class="img_box">
            
              <%= image_tag "Icon3.png"%>
              
          </div>
          <div class="text">
            <p>
                Set up your home page to Cingo.me
            </p>
          </div>
        </div>
        <div class="col-sm-3 feature last">
          <div class="img_box">
            
              <%= image_tag "Icon4.png"%>
            
          </div>
          <div class="text">
            <p>
                Select your website favicon and click on launch button
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index1.html.erb
<section id="feature_slider" class="lol">
  <!-- 
      Each slide is composed by <img> and .info
      - .info's position is customized with css in index.css
      - each <img> parallax effect is declared by the following params inside its class:
      
      example: class="asset left-472 sp600 t120 z3"
      left-472 means left: -472px from the center
      sp600 is speed transition
      t120 is top to 120px
      z3 is z-index to 3
      Note: Maintain this order of params

      For the backgrounds, you can combine from the bgs folder :D
  -->
  <article class="slide" id="showcasing" style="background: url('/assets/img/backgrounds/landscape.png') repeat-x top center;">
    <img class="asset left-30 sp600 t120 z1" src="/assets/img/slides/scene1/macbook.png" />
    <div class="info">
      <h2>Beautiful theme for showcasing your works.</h2>
    </div>
  </article>
  <article class="slide" id="ideas" style="background: url('/assets/img/backgrounds/aqua.jpg') repeat-x top center;">
    <div class="info">
      <h2>We love to turn ideas into beautiful things.</h2>
    </div>
    <img class="asset left-480 sp600 t260 z1" src="/assets/img/slides/scene2/left.png" />
    <img class="asset left-210 sp600 t213 z2" src="/assets/img/slides/scene2/middle.png" />
    <img class="asset left60 sp600 t260 z1" src="/assets/img/slides/scene2/right.png" />
  </article>
  <article class="slide" id="tour" style="background: url('/assets/img/backgrounds/color-splash.jpg') repeat-x top center;">
    <img class="asset left-472 sp650 t210 z3" src="/assets/img/slides/scene3/ipad.png" />
    <img class="asset left-365 sp600 t270 z4" src="/assets/img/slides/scene3/iphone.png" />
    <img class="asset left-350 sp450 t135 z2" src="/assets/img/slides/scene3/desktop.png" />
    <img class="asset left-185 sp550 t220 z1" src="/assets/img/slides/scene3/macbook.png" />
    <div class="info">
      <h2>Fully Responsive theme</h2>
      <a href="features.html">TOUR THE PRODUCT</a>
    </div>
  </article>
  <article class="slide" id="responsive" style="background: url('/assets/img/backgrounds/indigo.jpg') repeat-x top center;">
    <img class="asset left-472 sp600 t120 z3" src="/assets/img/slides/scene4/html5.png" />
    <img class="asset left-190 sp500 t120 z2" src="/assets/img/slides/scene4/css3.png" />
    <div class="info">
      <h2>
        Responsive <strong>HTML5 & CSS3</strong>
        Theme
      </h2>                
    </div>
  </article>        
</section>

<div id="showcase">
  <div class="container">
    <div class="section_header">
      <h3>Our Services</h3>
    </div>            
    <div class="row feature_wrapper">
      <!-- Features Row -->
      <div class="features_op1_row">
        <!-- Feature -->
        <div class="col-sm-4 feature first">
          <div class="img_box">
            <a href="services.html">
              <img src="/assets/img/service1.png">
              <span class="circle"> 
                  <span class="plus">&#43;</span>
              </span>
            </a>
          </div>
          <div class="text">
            <h6>Responsive theme</h6>
            <p>
                There are many variations of passages of generators on the  embarrassing hidden in   content here making it look like.
            </p>
          </div>
        </div>
        <!-- Feature -->
        <div class="col-sm-4 feature">
          <div class="img_box">
            <a href="services.html">
              <img src="/assets/img/service2.png">
              <span class="circle"> 
                  <span class="plus">&#43;</span>
              </span>
            </a>
          </div>
          <div class="text">
            <h6>Easy customization</h6>
            <p>
                There are many variations of passages of generators on the  embarrassing hidden in   content here making it look like.
            </p>
          </div>
        </div>
        <!-- Feature -->
        <div class="col-sm-4 feature last">
          <div class="img_box">
            <a href="services.html">
              <img src="/assets/img/service3.png">
              <span class="circle"> 
                <span class="plus">&#43;</span>
              </span>
            </a>
          </div>
          <div class="text">
            <h6>Made with love</h6>
            <p>
                There are many variations of passages of generators on the  embarrassing hidden in   content here making it look like.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="features">
  <div class="container">
    <div class="section_header">
      <h3>Features</h3>
    </div> 
    <div class="row feature">
      <div class="col-sm-6">
        <img src="/assets/img/showcase1.png" class="img-responsive" />
      </div>
      <div class="col-sm-6 info">
        <h3>
          <img src="/assets/img/features-ico1.png" />
              Beautiful on all devices
        </h3>
        <p>
          There are many variations of passages of Lorem Ipsum available, but the randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.
        </p>
      </div>
    </div>
    <div class="row feature">
      <div class="col-sm-6 pic-right">
        <img src="/assets/img/showcase2.png" class="pull-right img-responsive" />
      </div>
      <div class="col-sm-6 info info-left">
        <h3>
          <img src="/assets/img/features-ico2.png" />
          Blog page included
        </h3>
        <p>
          There are many variations of passages of Lorem Ipsum available, but the randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.
        </p>
      </div>                
    </div>
    <div class="row feature">
      <div class="col-sm-6">
        <img src="/assets/img/showcase3.png" class="img-responsive" />
      </div>
      <div class="col-sm-6 info">
        <h3>
          <img src="/assets/img/features-ico3.png" />
          Simple and clean coming soon page
        </h3>
        <p>
          There are many variations of passages of Lorem Ipsum available, but the randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.
        </p>
      </div>
    </div>
  </div>
</div>


<!-- Pricing Option -->
<div id="in_pricing">
  <div class="container">
    <div class="section_header">
      <h3>Pricing</h3>
    </div>

    <div class="row charts_wrapp">
      <!-- Plan Box -->
      <div class="col-sm-4">
        <div class="plan">
          <div class="wrapper">
            <h3>Lite</h3>
            <div class="price">
              <span class="dollar">$</span> 
              <span class="qty">35</span> 
              <span class="month">/month</span>
            </div>
            <div class="features">
              <p>
                <strong>10</strong>
                Shared Projects
              </p>
              <p>
                <strong>4</strong>
                Team Members
              </p>
              <p>
                <strong>10</strong>
                Storage
              </p>
            </div>
            <a class="order" href="pricing.html">ORDER NOW</a>
          </div>
        </div>
      </div>
          <!-- Plan Box -->
      <div class="col-sm-4 pro">
        <div class="plan">
          <div class="wrapper">
            <img class="ribbon" src="/assets/img/badge.png">
            <h3>Pro</h3>
            <div class="price">
              <span class="dollar">$</span> 
              <span class="qty">99</span> 
              <span class="month">/month</span>
            </div>
            <div class="features">
              <p>
                <strong>10</strong>
                Shared Projects
              </p>
              <p>
                <strong>25</strong>
                Team Members
              </p>
              <p>
                <strong>Unlimited</strong>
                 Storage
              </p>
              <p>
                <strong>Plus </strong>
                Phone Support
              </p>
            </div>
            <a class="order" href="pricing.html">ORDER NOW</a>
          </div>
        </div>
      </div>
      <!-- Plan Box -->
      <div class="col-sm-4 standar">
        <div class="plan">
          <div class="wrapper">
            <h3>Standard</h3>
            <div class="price">
                <span class="dollar">$</span> 
                <span class="qty">65</span> 
                <span class="month">/month</span>
            </div>
            <div class="features">
                <p>
                  <strong>10</strong>
                  Shared Projects
                </p>
                <p>
                  <strong>4</strong>
                  Team Members
                </p>
                <p>
                  <strong>10</strong>
                  Storage
                </p>
            </div>
            <a class="order" href="pricing.html">ORDER NOW</a>
          </div>
        </div>
      </div>
    </div>
    <div class="start">
      <p>Start your free, no-risk, 14 day trial! </p>
      <a href="pricing.html">Start Now!</a>
    </div>
  </div>
</div>

<div id="clients">
  <div class="container">
    <div class="section_header">
      <h3>Clients</h3>
    </div>
    <div class="row">
      <div class="col-md-2 col-sm-4 client">
        <div class="img client1"></div>
      </div>
      <div class="col-md-2 col-sm-4 client">
        <div class="img client2"></div>
      </div>
      <div class="col-md-2 col-sm-4 client">
        <div class="img client3"></div>
      </div>
      <div class="col-md-2 col-sm-4 client">
        <div class="img client1"></div>
      </div>
      <div class="col-md-2 col-sm-4 client">
        <div class="img client2"></div>
      </div>
      <div class="col-md-2 col-sm-4 client">
        <div class="img client3"></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Cingo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
  <!-- Styles -->
  <link href="/assets/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="/assets/css/compiled/bootstrap-overrides.css" type="text/css" />
  <link rel="stylesheet" type="text/css" href="/assets/css/compiled/theme.css" />

  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css' />

  <link rel="stylesheet" href="/assets/css/compiled/index.css" type="text/css" media="screen" />    
  <link rel="stylesheet" type="text/css" href="/assets/css/lib/animate.css" media="screen, projection" />    

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body class="pull_top">
  <script>
    $(document).ready(function(){
      $(window).scroll(function() {
        if ($(".navbar").offset().top>30) {
          $(".navbar-fixed-top").addClass("sticky");
        }
        else {
          $(".navbar-fixed-top").removeClass("sticky");
        }
      });

    });
  </script>
    
	<%= render partial: "/shared/header" %>
  <%= yield %>
  <%= render partial: "/shared/footer" %>
    <!-- Scripts -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/theme.js"></script>

    <script type="text/javascript" src="/assets/js/index-slider.js"></script>	
</body>
</html>

app/views/layouts/layout_header.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Cingo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
  <!-- Styles -->
  <link href="/assets/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="/assets/css/compiled/bootstrap-overrides.css" type="text/css" />
  <link rel="stylesheet" type="text/css" href="/assets/css/compiled/theme.css" />

  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css' />

  <link rel="stylesheet" href="/assets/css/compiled/index.css" type="text/css" media="screen" />    
  <link rel="stylesheet" type="text/css" href="/assets/css/lib/animate.css" media="screen, projection" />    
  <link rel="stylesheet" type="text/css" href="/assets/css/lib/animate.css" media="screen, projection" />
  <link rel="stylesheet" href="/assets/css/compiled/sign-up.css" type="text/css" media="screen" />

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body class="pull_top">
  <script>
    $(document).ready(function(){
      $(".navbar-fixed-top").addClass("sticky");
    });
  </script>
    
	<%= render partial: "/shared/header" %>
  <section class="body-section" style="min-height:25em">
    <%= yield %>
  </section>
  <%= render partial: "/shared/footer" %>
    <!-- Scripts -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/theme.js"></script>

    <script type="text/javascript" src="/assets/js/index-slider.js"></script>	
</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/websites/_form.html.erb
<%= form_for website do |f|%>
  <fieldset>
 	  	<div class="form-group">
 	  		<%= f.text_field :url,class: "form-control",placeholder: "URL of Website"%>
 	  		
 		</div>
 		<div class="form-group">
 		<%= f.text_field :user_name,class: "form-control", placeholder: "User name"%>
 	</div>
 		<div class="form-group">
 			<%= f.password_field :password,class: "form-control" ,placeholder: "Password" %>
 		</div>
 		<input class="btn btn-lg btn-success btn-block" type="submit" value="Submit">
 	</fieldset>
<%end%>

app/views/websites/edit.html.erb
<div class="container" style="margin-top:100px">
    <div class="row">
		<div class="col-md-4 col-md-offset-4">
    		<div class="panel panel-default">
			  	<div class="panel-heading">
			    	<h3 class="panel-title">Edit Website</h3>
			 	</div>
			  	<div class="panel-body">			    	
			    	<%= render partial: "form",locals: {website: @website}%>	
			    </div>
			</div>
		</div>
	</div>
</div>

app/views/websites/setup.html.erb
<div class="container">
    <h1>&nbsp;</h1>
      <div class="row">
        <div class="col-md-16">
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Your websites
              <!-- <button type="button" id="example" data-trigger = "hover" class="pull-right btn btn-default" data-container="body" data-toggle="popover" data-placement="top" data-content="Drag this to your bookmark bar and use for auto login.">
                ?</button> -->
            <%#= link_to "Cingo", get_link,style: "margin-left:10px;color: white",class: "btn btn-success pull-right"%>
            <%= link_to "Add new Website", new_website_path,class: "btn btn-success pull-right", style: "color: white;"%>
          </h3>

          </div>
          <table class="table table-hover" id="task-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Website</th>
                <th>Username</th>
                
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% current_user.websites.each_with_index do |website, index|%>
                <tr>
                  <td class><%= index+1 %></td>
                  <td class= "website-url"><%=link_to website.url, website.url ,target: "_blank"%></td>
                  <td><%= website.user_name %></td>
                  
                  <td><%=link_to "Edit", edit_website_path(website)%> | &nbsp;<%= link_to "Delete", website_path(website), method: "delete",confirm: "Are you sure"%> 
                    
                  </td>
                </tr> 
                <%end%>           
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <script>
$(document).ready(function(){
  $('#example').popover();
   $(".website-url").each(function() {
      $(this).prev().html("<a href ='"+$(this).text()+"' target='_blank'><img width='20px' height='20px' src='" + $(this).text() + "/favicon.ico' /></a>");
    });
  });
</script>